language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
  - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake -qt=qt5 GameRubiksClockConsole.pro
  - make --silent debug
  - ./GameRubiksClockConsole
  # Desktop
  - qmake -qt=qt5 GameRubiksClockDesktop.pro
  - make --silent debug
  - ./GameRubiksClockDesktop &
  - sleep 10
  - sudo killall GameRubiksClockDesktop
  # Website
  - qmake -qt=qt5 GameRubiksClockWebsite.pro
  - make --silent debug
  - ./GameRubiksClockWebsite &
  - sleep 10
  - sudo killall GameRubiksClockWebsite
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)